name: Inventory Service CI/CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ECR_REPOSITORY: 474221740713.dkr.ecr.ap-northeast-3.amazonaws.com/inventory-service_1
      IMAGE_TAG: latest
      AWS_REGION: ap-northeast-3
      CONTAINER_NAME: inventory-service_1
      EC2_PORT: 8082

    steps:
      # 1️⃣ Checkout inventory-service (child repo)
      - name: Checkout inventory-service
        uses: actions/checkout@v3

      # 2️⃣ Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # 3️⃣ Clone private parent repo (iotiq_edge) using PAT and install parent POM
      - name: Clone and install parent POM
        run: |
          git clone https://x-access-token:${{ secrets.PARENT_REPO_PAT }}@github.com/Chaitanya2872/iotiq_edge.git ../iotiq_edge
          cd ../iotiq_edge
          mvn clean install

      # 4️⃣ Build inventory-service
      - name: Build inventory-service
        run: mvn clean package

      # 5️⃣ AWS ECR login
      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ${{ env.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 6️⃣ Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REPOSITORY:$IMAGE_TAG

      # 7️⃣ Deploy to EC2
      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@15.168.240.206 "
            docker pull $ECR_REPOSITORY:$IMAGE_TAG
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            docker run -d -p $EC2_PORT:8082 --name $CONTAINER_NAME $ECR_REPOSITORY:$IMAGE_TAG
          "
