name: Inventory Service CI/CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ECR_REPOSITORY: 474221740713.dkr.ecr.ap-northeast-3.amazonaws.com/inventory-service_1
      IMAGE_TAG: latest
      AWS_REGION: ap-northeast-3
      CONTAINER_NAME: inventory-service_1
      EC2_PORT: 8082

    steps:
      # 1️⃣ Checkout the child repo
      - name: Checkout inventory-service
        uses: actions/checkout@v3

      # 2️⃣ Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # 3️⃣ Clone and install parent POM
      - name: Clone and install parent POM
        run: |
          git clone https://github.com/Chaitanya2872/iotiq_edge.git ../iotiq_edge
          cd ../iotiq_edge
          mvn clean install
        # Optional: If your parent POM repo is private, add SSH key or PAT

      # 4️⃣ Build inventory-service
      - name: Build inventory-service
        run: mvn clean package

      # 5️⃣ (Optional) Build Docker image and push to ECR
      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ${{ env.AWS_REGION }}

      - name: Build and Push Docker image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REPOSITORY:$IMAGE_TAG

      # 6️⃣ (Optional) Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@15.168.240.206 "
            docker pull $ECR_REPOSITORY:$IMAGE_TAG
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            docker run -d -p $EC2_PORT:8082 --name $CONTAINER_NAME $ECR_REPOSITORY:$IMAGE_TAG
          "
